FROM python:3
 
# If more labels are needed, don't use multiple LABEL statements. Instead extend this one
LABEL maintainer="Fatih Turkmen <turkmenf@gmail.com>"

# Add other directives here, for example RUN, COPY, CMD or ENTRYPOINT
COPY ./example-oauth2-server startContainer.sh /source/
WORKDIR /source

RUN apt-get update && \
    apt-get install -y git && \
    pip install -r requirements.txt && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
#    git clone https://github.com/fturkmen/example-oauth2-server.git && \
    chmod --verbose +x /source/startContainer.sh
 
# Be careful setting this to true since this enables the OAuth2 server to work 
# with HTTP (instead of HTTPS) which is something you may not want in production. 
ENV AUTHLIB_INSECURE_TRANSPORT=false 

EXPOSE 4005/tcp

CMD ["/source/startContainer.sh"]
